IMAGE_NAME = "fedora/34-cloud-base"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end
      
    config.vm.define "fedora" do |fedora|
        fedora.vm.box = IMAGE_NAME
        fedora.vm.network "private_network", ip: "192.168.56.10"
        fedora.vm.hostname = "fedora-docker"
        fedora.vm.provision "file", source: "./install-docker-playbook.yml", destination: "$HOME/"
        fedora.vm.provision "shell", inline: <<-SHELL
          echo "Install Ansible   --------------------"
          sudo yum install -y ansible
          sudo ansible-playbook install-docker-playbook.yml
        SHELL
    end

end
